name: Code Quality Check

# uncomment the line below to enable the workflow
# on: [pull_request]

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: ESLint check
        run: npm run lint
      - name: TypeScript check
        run: npm run typescript
